### ISSUE TITLE
"500 error" on "Variant Notes" and "Flag for Review" links

### ISSUE THREAD

**Issue by monkollek** [macarthur-lab/xbrowse#106] opened 2015-01-31 14:19 UTC
Can we have a more informative error page be displayed here or have some checks to make sure this link works for each project.

**Comment by bw2** [comment] 2015-02-01 03:19
Looking into this, the I can see the error on the website, and see the request appear in the logs as "GET /xbrowse/project/newcastle/variant-notes HTTP/1.1" 500"  but there's no django error message. Also, I can't reproduce this error on my local dev. instance.  @brettpthomas do you have any suggestions for this? If not, I will try turning on DEBUG=True tomorrow.

**Comment by bw2** [comment] 2015-03-23 16:13
Fixed on the ATGU server

**Closed by bw2** 2015-03-23 16:13 UTC
Labels: bug
